geodownloader: main.cpp  SignalHandler.h geoDownload.h DownloadItem.h DownloadItem.cpp
	g++ main.cpp -o geodownloader `pkg-config gtkmm-3.0 --cflags --libs` -std=c++0x -lboost_system -lboost_filesystem -lcurl -lcurlpp 
